version: "3.8"
services:
  nextjs:
    build: .
    container_name: zdorovaya-lapka-nextjs
    restart: unless-stopped
    environment:
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: zdorovaya-lapka-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/conf:/etc/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
    depends_on:
      - nextjs
    restart: unless-stopped
    networks:
      - app-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: zdorovaya-lapka-certbot
    volumes:
      - ./nginx/ssl/conf:/etc/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge
