version: "3.8"
services:
  nextjs:
    build: .
    container_name: zdorovaya-lapka-nextjs
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: zdorovaya-lapka-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/conf:/etc/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
    depends_on:
      - nextjs
    restart: unless-stopped
    networks:
      - app-network
    command: /bin/sh -c "nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: zdorovaya-lapka-certbot
    volumes:
      - ./nginx/ssl/conf:/etc/letsencrypt
      - ./nginx/ssl/www:/var/www/certbot
    restart: unless-stopped
    command: sh -c "trap exit TERM; while :; do certbot renew && docker exec zdorovaya-lapka-nginx nginx -s reload; sleep 12h; done"

networks:
  app-network:
    driver: bridge